const api = 'http://localhost:5000/api/'; 
export const environment = {
    production: false,
    hmr       : true,
    domain: api,
    login: api + 'login',
    register: api + 'registration',
    fileUploadApi: api + 'file_upload',
    getallemployee : api + 'getAllemployee',
    employee_create : api + 'employee_create',
    employee_getById : api + 'employee_getById',
    employee_update : api + 'employee_update',
    employee_delete : api + 'employee_create',
    getAllClient : api + 'getAllClient',
    client_create : api + 'client_create',
    client_getById : api + 'client_getById',
    client_update : api + 'client_update',
    client_delete : api + 'client_delete',
    getAllContructor : api + 'getAllContructor',
    contructor_create : api + 'contructor_create',
    contructor_getById : api + 'contructor_getById',
    contructor_update : api + 'contructor_update',
    contructor_delete : api + 'contructor_delete',
    create_task : api + 'create_task',
    task_list : api + 'task_list',
    getAlltask : api + 'getAlltask',
    task_getById : api + 'task_getById',
    task_update : api + 'task_update',
    task_delete : api + 'task_delete',
    create_project : api + 'create_project',
    getAllproject : api + 'getAllproject',
    project_getById : api + 'project_getById',
    project_update : api + 'project_update',
    p_costDurationUpdate : api + 'p_costDurationUpdate',
    project_delete : api + 'project_delete',
    createNew_project_task : api + 'createNew_project_task',
    createNewSubtask : api + 'createNewSubtask',
    updateNewSubtask : api + 'updateNewSubtask',
    taskstatusChange : api + 'taskstatusChange',
    add_resource : api + 'add_resource',
    deleteResource : api + 'deleteResource',
    getresourceList : api + 'getresourceList',
    getProjectInvioced : api + 'getProjectInvioced',
    saveInvoiced : api + 'saveInvoiced',
    getAllInvoiced : api + 'getAllInvoiced',
    getOnlyprojects : api + 'getOnlyprojects',
    createPayment : api + 'createPayment',
    getAllTransaction : api + 'getAllTransaction',
    create_department : api + 'create_department',
    getDepartmentlist : api + 'getDepartmentlist',
    department_getById : api + 'department_getById',
    create_designation : api + 'create_designation',
    designation_getById : api + 'designation_getById',
    getdesignationlist : api + 'getdesignationlist',
    update_department : api + 'update_department',
    update_designation : api + 'update_designation',
    salary_insert : api + 'salary_insert',
    salary_update : api + 'salary_update',
    salary_data_list : api + 'salary_data_list',
    salaryData_getById : api + 'salaryData_getById',
    salary_payroll_list : api + 'salary_payroll',
    payroll_create : api + 'payroll_create',
    invMaterialSold :  api + 'invMaterialSold',
};
