
export class CalendarTable
{

    public static data = [
                {   id       : 1,
                    start    : '2021-09-03 10:00:00',
                    end      : '2021-09-03 14:37:00',
                    title    : 'A One day event',
                    allDay   : false,
                    color_primary  : '#F44336',
                    color_secondary: '#FFCDD2',
                    res_beforeStart: true,
                    res_afterEnd   : true,
                    draggable: true,
                    location: 'Los Angeles',
                    notes   : 'Eos eu verear adipiscing, ex ornatus denique iracundia sed, quodsi oportere appellantur an pri.',
                    ref_project : null
                },
                {   id       : 2,
                    start    : '2021-09-04 15:00:00',
                    end      : '2021-09-06 20:37:00',
                    title    : 'A two day event',
                    allDay   : false,
                    color_primary  : '#F44336',
                    color_secondary: '#FFCDD2',
                    res_beforeStart: true,
                    res_afterEnd   : true,
                    draggable: true,
                    location: 'Los Angeles',
                    notes   : 'Eos eu verear adipiscing, ex ornatus denique iracundia sed, quodsi oportere appellantur an pri.',
                    ref_project : null
                },
                {   id       : 3,
                    start    : '2021-09-13 10:00:00',
                    end      : '2021-09-18 14:37:00',
                    title    : 'A Three day event',
                    allDay   : false,
                    color_primary  : '#F44336',
                    color_secondary: '#FFCDD2',
                    res_beforeStart: true,
                    res_afterEnd   : true,
                    draggable: true,
                    location: 'Los Angeles',
                    notes   : 'Eos eu verear adipiscing, ex ornatus denique iracundia sed, quodsi oportere appellantur an pri.',
                    ref_project : null
                },
                {   id       : 4,
                    start    : '2021-09-03 10:00:00',
                    end      : '2021-09-03 14:37:00',
                    title    : 'Nice event',
                    allDay   : true,
                    color_primary  : '#F44336',
                    color_secondary: '#FFCDD2',
                    res_beforeStart: true,
                    res_afterEnd   : true,
                    draggable: true,
                    location: 'Los Angeles',
                    notes   : 'Eos eu verear adipiscing, ex ornatus denique iracundia sed, quodsi oportere appellantur an pri.',
                    ref_project : null
                },
                {   id       : 5,
                    start    : '2021-09-03 10:00:00',
                    end      : '2021-09-03 14:37:00',
                    title      : 'Something day event',
                    allDay   : false,
                    color_primary  : '#F44336',
                    color_secondary: '#FFCDD2',
                    res_beforeStart: true,
                    res_afterEnd   : true,
                    draggable: true,
                    location: 'Los Angeles',
                    notes   : 'Eos eu verear adipiscing, ex ornatus denique iracundia sed, quodsi oportere appellantur an pri.',
                    ref_project : null
                },
               
    ];
}
